//Pruebas de peticiones al servidor

//Peticiones de la ruta /api/empleados

//Recuperar todos los empleados
GET http://localhost:3000/api/empleados


###

//Crear un nuevo empleado
POST http://localhost:3000/api/empleados
Content-Type: application/json

{
    "nombre": "Ana",
    "dni": "12345678A",
    "sexo": "F",
    "fecha_nacimiento": "1985-05-11",
    "salario": 3500,
    "cargo": "mantenimiento",
    "departamento": 1,
    "jefe_id": null
}

###

//Eliminar empleado elegido por id
DELETE http://localhost:3000/api/empleados/28

###

//Actualizar empleado elegido por id
PUT http://localhost:3000/api/empleados/1
Content-Type: application/json

{
    
    "nombre": "Ivan",
    "dni": "03145245H",
    "sexo": "M",
    "fecha_nacimiento": "1993-11-13",
    "fecha_incorporacion": "2020-06-30",
    "salario": 7000,
    "cargo": "desarrollador",
    "fk_departamento": 1,
    "jefe_id": 4
}
###
//Peticiones de la ruta /api/departamentos

//Recuperar todos los departamentos
GET http://localhost:3000/api/departamentos

###

//Eliminar departamento elegido por id
DELETE http://localhost:3000/api/departamentos/7

###

//Crear departamento
POST http://localhost:3000/api/departamentos/
Content-Type: application/json

{
    "nombre": "Recursos humanos",
    "ciudad": "Málaga"
}

###

//Editar departamento elegido por id
PUT http://localhost:3000/api/departamentos/3
Content-Type: application/json

{
    "nombre": "Finanzas",
    "ciudad": "Madrid"
}

